INSERT INTO TASKS(ID, PROJECT_ID, NAME, COMPLETE) VALUES (1, 1, 'Tesla Testing', true);

INSERT INTO TASKS(ID, PROJECT_ID, NAME, COMPLETE) VALUES (2, 2, 'Apple Testing', true);

INSERT INTO TASKS(ID, PROJECT_ID, NAME, COMPLETE) VALUES (3, 3, 'Apple Testing', true);

INSERT INTO TASKS(ID, PROJECT_ID, NAME, COMPLETE) VALUES (4, 4, 'Apple Testing', true);

INSERT INTO TASKS(ID, PROJECT_ID, NAME, COMPLETE) VALUES (5, 5, 'Honda Testing', true);

SELECT * FROM TASKS;